import { Request } from 'express';

export enum UserRole {
  ADMIN = 'ADMIN',
  USER = 'USER',
}

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
}

export enum AssetStatus {
  AVAILABLE = 'AVAILABLE',
  IN_USE = 'IN_USE',
  MAINTENANCE = 'MAINTENANCE',
  DECOMMISSIONED = 'DECOMMISSIONED',
  DISPOSED = 'DISPOSED',
}

export enum MaintenanceType {
  PREVENTIVE = 'PREVENTIVE',
  CORRECTIVE = 'CORRECTIVE',
  INSPECTION = 'INSPECTION',
  CALIBRATION = 'CALIBRATION',
  CLEANING = 'CLEANING',
}

export enum MaintenanceStatus {
  SCHEDULED = 'SCHEDULED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  OVERDUE = 'OVERDUE',
}

export enum PurchaseStatus {
  DRAFT = 'DRAFT',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  PURCHASED = 'PURCHASED',
  CANCELLED = 'CANCELLED',
}

export enum PurchasePriority {
  LOW = 'LOW',
  NORMAL = 'NORMAL',
  HIGH = 'HIGH',
  URGENT = 'URGENT',
}

export enum InventoryStatus {
  DRAFT = 'DRAFT',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum InventoryItemStatus {
  PENDING = 'PENDING',
  FOUND = 'FOUND',
  NOT_FOUND = 'NOT_FOUND',
  DISCREPANCY = 'DISCREPANCY',
}

export interface AuthUser {
  id: string;
  email: string;
  name: string;
  role: UserRole;
  status: UserStatus;
}

export interface AuthRequest extends Request {
  user?: AuthUser;
}

export enum AuditAction {
  // Auth
  USER_LOGIN = 'USER_LOGIN',
  USER_LOGOUT = 'USER_LOGOUT',
  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  USER_DEACTIVATED = 'USER_DEACTIVATED',
  USER_ACTIVATED = 'USER_ACTIVATED',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',

  // Assets
  ASSET_CREATED = 'ASSET_CREATED',
  ASSET_UPDATED = 'ASSET_UPDATED',
  ASSET_MOVED = 'ASSET_MOVED',
  ASSET_ASSIGNED = 'ASSET_ASSIGNED',
  ASSET_UNASSIGNED = 'ASSET_UNASSIGNED',
  ASSET_DECOMMISSIONED = 'ASSET_DECOMMISSIONED',
  ASSET_DISPOSED = 'ASSET_DISPOSED',

  // Maintenance
  MAINTENANCE_CREATED = 'MAINTENANCE_CREATED',
  MAINTENANCE_STARTED = 'MAINTENANCE_STARTED',
  MAINTENANCE_COMPLETED = 'MAINTENANCE_COMPLETED',
  MAINTENANCE_CANCELLED = 'MAINTENANCE_CANCELLED',

  // Inventory
  INVENTORY_CREATED = 'INVENTORY_CREATED',
  INVENTORY_STARTED = 'INVENTORY_STARTED',
  INVENTORY_COMPLETED = 'INVENTORY_COMPLETED',
  INVENTORY_ITEM_CHECKED = 'INVENTORY_ITEM_CHECKED',

  // Categories & Locations
  CATEGORY_CREATED = 'CATEGORY_CREATED',
  CATEGORY_UPDATED = 'CATEGORY_UPDATED',
  CATEGORY_DELETED = 'CATEGORY_DELETED',
  LOCATION_CREATED = 'LOCATION_CREATED',
  LOCATION_UPDATED = 'LOCATION_UPDATED',
  LOCATION_DELETED = 'LOCATION_DELETED',

  // Procurement
  PURCHASE_CREATED = 'PURCHASE_CREATED',
  PURCHASE_UPDATED = 'PURCHASE_UPDATED',
  PURCHASE_SUBMITTED = 'PURCHASE_SUBMITTED',
  PURCHASE_APPROVED = 'PURCHASE_APPROVED',
  PURCHASE_REJECTED = 'PURCHASE_REJECTED',
  PURCHASE_EXECUTED = 'PURCHASE_EXECUTED',
  PURCHASE_CANCELLED = 'PURCHASE_CANCELLED',

  // Suppliers
  SUPPLIER_CREATED = 'SUPPLIER_CREATED',
  SUPPLIER_UPDATED = 'SUPPLIER_UPDATED',
  SUPPLIER_ARCHIVED = 'SUPPLIER_ARCHIVED',
}
